### ISSUE TITLE
etcdLock mutex not unlocked on some code paths

### ISSUE THREAD

**Issue by daniel-ziegler** [datawisesystems/etcd-lock#7]
In `etcdLock.Start()`, if `e.enabled` is true, the function returns without unlocking (see https://github.com/datawisesystems/etcd-lock/blob/master/master.go#L110). The same thing happens in `etcdLock.Stop()` if `e.enabled` is false.

**Comment by nelcy** [comment]
Thanks Daniel.. Fixed it.. Waiting to merge..

**Comment by ravigadde** [comment]
Fixed by #8
